# Generated by Django 3.2.6 on 2021-08-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiza', '0006_alter_rachunki_waluta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rachunki',
            name='waluta',
            field=models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR')], default='', max_length=4),
        ),
    ]
