# Generated by Django 3.2.6 on 2021-08-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rachunki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(default='', max_length=1150)),
                ('rodzaj_operaji', models.CharField(default='', max_length=1150)),
                ('kwota', models.PositiveSmallIntegerField(default=0)),
                ('waluta', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR')], default='', max_length=4)),
                ('konto_zrodlowe', models.CharField(default='', max_length=100)),
                ('konto_docelowe', models.CharField(default='', max_length=100)),
                ('data_realizacji', models.DateField(blank=True, null=True)),
                ('data_zlecenia_przelewu', models.DateField(blank=True, null=True)),
                ('zleceniodawca', models.CharField(default='', max_length=1500)),
                ('beneficjent', models.CharField(default='', max_length=1550)),
                ('kod_rodzaju_transakcji', models.CharField(default='', max_length=1200)),
            ],
        ),
    ]
