# Generated by Django 3.2.6 on 2021-08-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analiza', '0018_alter_rachunki_waluta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rachunki',
            name='kwota',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10000000, null=True),
        ),
    ]
